사용자 프로필 및 팔로우 확인 Api 개발
service-dida/back_end pull request #117
Opened 2023-06-27 10:15 UTC by JuneYoungDo

### 요약

- 사용자 프로필 및 팔로우 확인 Api 개발
### 상세 내용

- 내 프로필 확인하기 Api
- 내 프로필 NFT 목록 확인하기 Api
- 타인 프로필 확인하기 Api
- 타인 NFT 목록 확인하기 Api
- 다른 유저 팔로우 및 팔로우, 팔로잉 목록 확인하기 Api
- Follow의 memberId 부분을 member 로 변경 -> 팔로우 멤버들의 정보를 가져와야 하는데 id 값들을 가져온 후 다시 id에 맞는 유저정보를 가져온다면 너무나 비 효율적이라 수정하였습니다.
### 질문 및 이외 사항

- 
### 이슈 번호

- #11 #12 #13 #14 #15 #16 #17

2023-06-27 18:55 UTC, YooJisu826 requested changes
고생하셨습니당!!

2023-06-27 18:55 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/nft/service/GetNftService.java
> +    }
피그마에서 보니까 프로필에서 내가 소유한 NFT는 최신순/오래된순 이렇게 두 가지로 정렬할 수 있게 되어있더라고요!!

어떤 순으로 요청냐에 따라서, PageRequest를 만들 때 정렬 방식만 수정해서 내려줄 수 있도록 코드 수정이 필요할 것 같습니다!!

2023-06-27 18:55 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/nft/dto/NftResponseDto.java
> +        private boolean liked;
이 NftInfo가 제가 커뮤니티에서 사용하려고 만든 건데, 커뮤니티에서 보여지는 NFT 정보에는 소유주의 닉네임이 필요하지 않아요!! 

그런데 피그마 상에서 프로필 NFT를 불러올 때는 소유주의 이름도 필요한걸로 되어 있습니당!! 자기 꺼 확인할 때 소유주 이름이 무슨 의미인지는 모르겠지만.... 피그마 상대로 하시려면 소유주 이름 추가하셔야 될 거 같습니닷!!

2023-06-27 18:55 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/follow/controller/FollowController.java
> +    @PatchMapping("/member/follow/{memberId}")
HTTP Method patch 쓰신 이유 궁금합니당!!

2023-06-27 18:55 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/member/entity/Member.java
> +    }
this.nfts.size() 하면 deleted = true인 애들도 카운팅되지 않나요?!

2023-06-28 06:26 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/nft/service/GetNftService.java
> +    }
넵넵 우선 요렇게 만들어두고, 문제없으면 해당 기능 추가할 예정입니다..!

2023-06-28 06:26 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/nft/dto/NftResponseDto.java
> +        private boolean liked;
우선 소유주 이름은 안쓰는걸로 전에 톡방에서 얘기가 되었었습니다..! 하여 우선은 제외했습니다 :)

2023-06-28 06:27 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/follow/controller/FollowController.java
> +    @PatchMapping("/member/follow/{memberId}")
사실 어떤걸 써야하나 고민이 되었는데 일단상태 업데이트라고 생각해서 patch를 사용했습니다..다른걸 사용하는게맞는걸까요??

2023-06-28 06:27 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/member/entity/Member.java
> +    }
엇 그렇네요, 해당부분 수정이 필요하겠군요

2023-06-28 11:09 UTC, YooJisu826 approved these changes
고생하셨습니당!!

2023-06-28 11:09 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/member/entity/Member.java
> +        int nftSize = (int) nfts.stream().filter(nft -> !nft.isDeleted()).count();
옹 제가 잘 못쓰는 문법... 배워갑니당

2023-06-28 11:10 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/follow/controller/FollowController.java
> +    @PatchMapping("/member/follow/{memberId}")
저는 첨엔 POST로 하긴 했습니다...ㅠ 저도 잘 모르겠어서 여쭤본건데 헷갈리긴 하네요!!

2023-06-28 11:11 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/nft/dto/NftResponseDto.java
> +        private boolean liked;
그렇군요....!!!!!!

2023-06-28 13:53 UTC, merged