Feat: 최신 버전 확인 API
service-dida/back_end pull request #158
Opened 2023-12-20 16:32 UTC by YooJisu826

### 요약

- 최신 버전을 확인하는 API입니다.
### 상세 내용
- 다음과 같이 내려갑니다.
```json
{
    "versionId" : 1,
    "version": "1.0.0",
    "changes": "최초 버전입니다.",
    "essentialUpdate": false
}
```
- 현재 버전의 Id를 받아 비교하여 업데이트가 필요하다면 `essentialUpdate`를 true로 내려줍니다.
- `changes`에는 변경 사항이 내려갑니다. 1.0.0 버전은 최초 버전이라고 표시했습니다.
### 질문 및 이외 사항

-

2023-12-22 16:18 UTC, JuneYoungDo requested changes

2023-12-22 16:18 UTC, JuneYoungDo commented on src/main/java/com/service/dida/global/common/version/VersionService.java
버전 생성과 관련된 부분이 없는것은 자체적으로 저희가 디비에 데이터를 넣을것이라 그런것일까요?

2023-12-22 16:18 UTC, JuneYoungDo commented on src/main/java/com/service/dida/global/common/version/VersionRepository.java
> +    int countsByLaterVersion(@Param("time") LocalDateTime time);
@ Param 부분은 명시해주려고 써준건가용?

2023-12-22 16:18 UTC, JuneYoungDo commented on src/main/java/com/service/dida/global/common/version/VersionService.java
> +    private boolean checkUpdate(Long versionId) {
해당함수는 필수 업데이트만을 반영하는건가요?

2023-12-22 16:18 UTC, JuneYoungDo commented on src/main/java/com/service/dida/global/common/version/VersionService.java
> +        return versionRepository.countsByLaterVersion(version.getCreatedAt()) > 0;
여기서 필수업데이트가 아닌 자체적인 업데이트가 있어도  true가 나오게 되지 않나요..?

2023-12-27 07:29 UTC, YooJisu826 commented on src/main/java/com/service/dida/global/common/version/VersionService.java
넵 필요하다면 만들겠습니당!

2023-12-27 07:31 UTC, YooJisu826 commented on src/main/java/com/service/dida/global/common/version/VersionRepository.java
> +    int countsByLaterVersion(@Param("time") LocalDateTime time);
넵 버전에 따라 작성하지 않으면 에러가 나는 경우가 있더라구요 
명시적으로 작성하는게 더 좋은 것 같아 작성했습니다

2023-12-27 07:32 UTC, YooJisu826 commented on src/main/java/com/service/dida/global/common/version/VersionService.java
> +        return versionRepository.countsByLaterVersion(version.getCreatedAt()) > 0;
필수 업데이트와 자체 업데이트를 동일하다고 생각했는데 무슨 차이가 있는걸까요??

2023-12-27 07:32 UTC, YooJisu826 commented on src/main/java/com/service/dida/global/common/version/VersionService.java
> +    private boolean checkUpdate(Long versionId) {
아래 댓글과 동일한 답변입니다!

2023-12-27 07:33 UTC, YooJisu826 commented on src/main/java/com/service/dida/global/common/version/VersionService.java
> +    private boolean checkUpdate(Long versionId) {
헉 제가 아래 댓글을 Resolve 처리해버렸네요..!

필수 업데이트와 자체 업데이트 다른 점이 뭔가요..?

2024-01-02 04:51 UTC, JuneYoungDo commented on src/main/java/com/service/dida/global/common/version/VersionService.java
> +    private boolean checkUpdate(Long versionId) {
이제 내부적으로 리팩토링을 했다거나 사소하게 코드를 바꿔서 클라이언트 입장에서는 업데이트가 필요하지 않다면 자체업데이트가 될테고, 만약 기능적인 부분이 바뀌거나 새로운 내용이 추가되어서 클라이언트가 업데이트가 필수적이게 된다면 필수업데이트가 되지 않을까요?

2024-01-04 11:48 UTC, JuneYoungDo approved these changes
고생하셨습니당

2024-01-04 11:48 UTC, merged