댓글 관련 API 구현
service-dida/back_end pull request #96
Opened 2023-05-28 19:30 UTC by YooJisu826

### 요약

- 댓글 관련 API 구현
### 상세 내용

- 댓글 작성하기 API 구현
- 댓글 삭제하기 API 구현
- 게시글 별 댓글 조회 API 구현 (페이징 처리 O)
- 게시글 별 댓글 미리 보기 메서드 구현
### 질문 및 이외 사항

- 
### 이슈 번호

- close #56 close #57 close #58

2023-05-29 17:41 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/comment/repository/CommentRepository.java
> +    Page<Comment> findByPostIdWithDeleted(Long postId, PageRequest pageRequest);
이게 제가 처음에 네이밍을 이렇게 해서 이렇게 하시는거 같은데 아마 findByPostIdAndDeleted로 JPA에서 함수를 제공하긴 할거에요..! 나중에 수정할만하면 수정하는것도 괜찮을거 같습니다 ㅎㅎ...

2023-05-29 17:41 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/comment/service/GetCommentService.java
> +            if (commentCounts == 0) break;
if문과 아래의 commentCount--를 한줄로 할수있지않을까요..?!

2023-05-29 17:41 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/comment/service/UpdateCommentService.java
> +        if (memberId.equals(ownerId)) {
단순 값비교는 == 로도 할수 있지 않나요..?!
equals를 사용한 이유가 있나요??

2023-05-30 13:12 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/comment/controller/UpdateCommentController.java
> +            @RequestParam("commentId") Long commentId)
조회는 @RequestBody로 페이징 Request를 받아야해서 @PathVariable로 했고 
삭제는 받아올 게 없어서 @RequestParam으로 하긴 했습니다..! 통일할까요>?!

2023-05-30 13:13 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/comment/repository/CommentRepository.java
> +    Page<Comment> findByPostIdWithDeleted(Long postId, PageRequest pageRequest);
일괄 수정하겠습니다!

2023-05-30 13:18 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/comment/repository/CommentRepository.java
> +    Page<Comment> findByPostIdWithDeleted(Long postId, PageRequest pageRequest);
수정하려다보니... boolean deleted라는 파라미터를 하나씩 더 써줘야하는 것 같아서 그냥 수정 안 했습니다!!!!!!

2023-05-30 13:21 UTC, YooJisu826 commented on src/main/java/com/service/dida/domain/comment/service/UpdateCommentService.java
> +        if (memberId.equals(ownerId)) {
습관이 돼서 그랬는데 다음부터 참고하겠씁니다!!

2023-05-30 14:56 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/comment/controller/UpdateCommentController.java
> +            @RequestParam("commentId") Long commentId)
저도 확신이 안들긴하네요, 정보를 어디에 남아서 받느냐의 차이인데...흠..

2023-05-30 14:58 UTC, JuneYoungDo requested changes

2023-05-30 14:58 UTC, JuneYoungDo commented on src/main/java/com/service/dida/domain/comment/service/GetCommentService.java
>              type = "NEED LOGIN";
애초에 로그인을 하지 않는다면 member에 null값이 오게 됩니다. 하여 member.getMemberId()를 사용하면 에러가 발생할 것으로 생각됩니다. 다른부분들도 마찬가지입니다..!

2023-05-30 15:09 UTC, JuneYoungDo approved these changes

2023-05-30 15:10 UTC, JuneYoungDo commented
고생하셨습니다~

2023-05-30 15:10 UTC, merged